# Generated by Django 2.2.16 on 2022-09-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220925_1833'),
        ('reviews', '0002_auto_20220926_1317'),
    ]

    operations = [
    ]
