# Generated by Django 2.2.16 on 2022-09-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220926_1935'),
        ('reviews', '0002_auto_20220928_2133'),
    ]

    operations = [
    ]
